services:
    database:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - dev
        volumes:
            - data:/var/lib/mysql
    phpmyadmin:
        container_name: api-phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            PMA_ARBITRARY: 1
        networks:
            - dev
        depends_on:
            - database

    web:
        container_name: api-web
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${API_PORT}:80
        volumes:
            - ./:/var/www
        networks:
            - dev
        depends_on:
            - database

volumes:
    data:

networks:
  dev:
    name: dev
    # Iniciamos primero el backed y por tanto no hace falta. Si queremos ponerlo, realizar primero docker network create dev para tener la red
    # name: dev
    # external: true
